Expense/Expense/Controllers/AuditLogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Broadvine.DAL;
using Broadvine.Models.Expense;

namespace Expense.Controllers
{
    public class AuditLogsController : Controller
    {
        private BroadvineContext db = new BroadvineContext();

        // GET: AuditLogs
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Invoice()
        {
            return View();
        }

        public ActionResult System()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Expense/Expense/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Broadvine.DAL;
using Broadvine.Models.Expense;

namespace Expense.Controllers
{
    public class HomeController : Controller
    {
        private BroadvineContext db = new BroadvineContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Expense/Expense/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Expense/Expense/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Expense/Expense/Views/Home/Index.cshtml
@section Scripts {
    <script src="@Url.Content("~/Scripts/Dashboard.js")"></script>
}
<div class="row" id="workflow-stats"></div>

<div class="row">
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title" id="period-header">Current Posting Period</h3>
                <div class="right">
                    <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
                </div>
            </div>
            <div class="panel-body no-padding text-center">
                <div class="weekly-summary col-md-4">
                    <span class="number" id="period-count"><span class="glyphicon glyphicon-refresh spinning"></span></span>
                    <span class="info-label">Total Invoices</span>
                </div>
                <div class="weekly-summary col-md-4">
                    <span class="number" id="period-paid"><span class="glyphicon glyphicon-refresh spinning"></span></span>
                    <span class="info-label">Paid</span>
                </div>
                <div class="weekly-summary col-md-4">
                    <span class="number" id="period-void"><span class="glyphicon glyphicon-refresh spinning"></span></span>
                    <span class="info-label">Void</span>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Recent Invoice Activity</h3>
                <div class="right">
                    <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
                </div>
            </div>
            <div class="panel-body no-padding table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Invoice</th>
                            <th>User</th>
                            <th class="text-right">Amount</th>
                            <th>Date &amp; Time</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody id="activity-invoice">
                        <tr><td colspan="5"><span class="glyphicon glyphicon-refresh spinning"></span></td></tr>
                    </tbody>
                </table>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-md-6"><span class="panel-note"><i class="fa fa-clock-o"></i> Last 10 Entries</span></div>
                    <div class="col-md-6 text-right">
                        @Html.ActionLink("View All Activity", "Invoice", "AuditLogs", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Recent Overall Activity</h3>
                <div class="right">
                    <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
                </div>
            </div>
            <div class="panel-body no-padding table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Source</th>
                            <th>Type</th>
                            <th>Information</th>
                        </tr>
                    </thead>
                    <tbody id="activity-system">
                        <tr><td colspan="5"><span class="glyphicon glyphicon-refresh spinning"></span></td></tr>
                    </tbody>
                </table>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-md-6"><span class="panel-note"><i class="fa fa-clock-o"></i> Last 10 Entries</span></div>
                    <div class="col-md-6 text-right">
                        @Html.ActionLink("View All Activity", "System", "AuditLogs", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    
</div>