Expense/Expense/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Globalization;
using Broadvine.DAL;
using Broadvine.Models.Expense;
using Broadvine.Common.Helpers;

namespace Expense.Controllers
{
    public class InvoicesController : Controller
    {
        private BroadvineContext db = new BroadvineContext();

        // GET: Invoices
        public ActionResult Index()
        {
            //  Invoice status  
            int status = Request["status"] == null ? 0 : int.Parse(Request["status"].ToString());
            var months = new SelectList(Enumerable.Range(1, 12).Select(x => new SelectListItem()
                                                                            {
                                                                                Text = CultureInfo.CurrentCulture.DateTimeFormat.MonthNames[x - 1],
                                                                                Value = x.ToString(),
                                                                                Selected = (x == DateTime.Now.Month),
                                                                            }), "Value", "Text");
            
            ViewBag.SearchMonth = months;
            ViewBag.Status = status;
            ViewBag.StatusName = ((InvoiceStatus)status).ToString();

            return View();
        }

        public ActionResult Search(string searchterm)
        {
            return View();
        }

        // GET: Invoices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }

            ViewBag.Status = (int)invoice.StatusID;
            ViewBag.StatusName = invoice.StatusID.ToString();
            ViewBag.AuditLog = db.AuditLog.Where(a => a.InvoiceID == id).ToList();

            if (invoice.StatusID == InvoiceStatus.Pending)
                ViewBag.ShowNext = db.Invoices.Count(i => i.StatusID == InvoiceStatus.Pending && i.InvoiceID != invoice.InvoiceID) > 0;
            else ViewBag.ShowNext = false;

            IEnumerable<int> ids = from a in db.Attachments
                                   where a.InvoiceID == id
                                   select a.AttachmentID;
            ViewBag.AttachmentID = String.Join(",", ids.ToArray<int>());

            Attachment attachment = db.Attachments.FirstOrDefault(a => a.InvoiceID == id);
            if (attachment != null) ViewBag.Image = string.Format("{0}{1}", Core.RootStorage, attachment.FileLocation);
            
            return View(invoice);
        }

        // GET: Invoices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Invoices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "InvoiceID,InvoiceGuidA,InvoiceGuidB,PropertyID,StatusID,VendorID,DocumentID,InvoiceNumber,AccountNumber,InvoiceDate,DueDate,PostPeriod,Notes,CheckNumber,CheckDate,SubTotal,TaxTotal,ShippingTotal,NetTotal,BuyerFirstName,BuyerLastName,ReceivedDate,PostedDate,URL,Transmitted,TransmittedDate")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Invoices.Add(invoice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(invoice);
        }

        // GET: Invoices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View(new Invoice());
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InvoiceID,InvoiceGuidA,InvoiceGuidB,PropertyID,StatusID,VendorID,DocumentID,InvoiceNumber,AccountNumber,InvoiceDate,DueDate,PostPeriod,Notes,CheckNumber,CheckDate,SubTotal,TaxTotal,ShippingTotal,NetTotal,BuyerFirstName,BuyerLastName,ReceivedDate,PostedDate,URL,Transmitted,TransmittedDate")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invoice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(invoice);
        }

        // GET: Invoices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoice invoice = db.Invoices.Find(id);
            db.Invoices.Remove(invoice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Reject")]
        public ActionResult Reject(string guidA, string guidB, string reason, string next)
        {
            bool result = true;
            string message = "Invoice Rejected Successfully";
            int currentPropertyID = 0;
            int nextId = 0;
            InvoiceStatus currentStatus = InvoiceStatus.Pending;
            
            try
            {
                Invoice invoice = db.Invoices.FirstOrDefault(i => i.InvoiceGuidA.ToString() == guidA && i.InvoiceGuidB.ToString() == guidB);
                if (invoice != null)
                {
                    currentPropertyID = invoice.PropertyID;
                    currentStatus = invoice.StatusID ?? InvoiceStatus.Pending;
                    invoice.StatusID = InvoiceStatus.Rejected;
                    invoice.Notes += string.Format("{0}[{1} REJECTED - {2}]{0}{3}", Environment.NewLine, DateTime.Now.ToString("MM/dd/yyyy HH:mm:ss"), HttpContext.User.Identity.Name, reason);
                    invoice.Transmitted = false;
                    invoice.RejectedReason = reason;
                    db.SaveChanges();

                    Core.AddAuditEntry(db, AuditSource.User, AuditType.Info, "Rejected", reason, invoice.InvoiceID, invoice.VendorID, invoice.PropertyID, HttpContext.User.Identity.Name);
                }
            }
            catch (Exception e)
            {
                result = false;
                message = string.Format("An error occurred while rejecting the invoice.");
            }

            if (!string.IsNullOrEmpty(next) && bool.Parse(next))
            {
                var nextInvoice = db.Invoices.FirstOrDefault(i => i.StatusID == currentStatus && i.PropertyID == currentPropertyID);
                if (nextInvoice != null) nextId = nextInvoice.InvoiceID;
            }

            return Json(new { passed = result, message = message, id = nextId });
        }

        [HttpPost, ActionName("Post")]
        public ActionResult Post(string guidA, string guidB, string next)
        {
            bool result = true;
            string message = "Invoice Posted Successfully";
            int currentPropertyID = 0;
            int nextId = 0;
            InvoiceStatus currentStatus = InvoiceStatus.Pending;

            try
            { 
                Invoice invoice = db.Invoices.FirstOrDefault(i => i.InvoiceGuidA.ToString() == guidA && i.InvoiceGuidB.ToString() == guidB);
                if (invoice != null)
                {
                    currentPropertyID = invoice.PropertyID;
                    invoice.StatusID = InvoiceStatus.Post;
                    db.SaveChanges();

                    Core.AddAuditEntry(db, AuditSource.User, AuditType.Info, "Post", "", invoice.InvoiceID, invoice.VendorID, invoice.PropertyID, HttpContext.User.Identity.Name);
                }
            }
            catch (Exception e)
            {
                    result = false;
                    message = string.Format("An error occurred while posting the invoice.");
            }

            if (!string.IsNullOrEmpty(next) && bool.Parse(next))
            {
                var nextInvoice = db.Invoices.FirstOrDefault(i => i.StatusID == currentStatus && i.PropertyID == currentPropertyID);
                if (nextInvoice != null) nextId = nextInvoice.InvoiceID;
            }

            return Json(new { passed = result, message = message, id = nextId });
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Expense/Expense/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <title>Expense - Dashboard</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    @Styles.Render("~/Content/css")
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="Content/Images/apple-icon.png">
    <link rel="icon" type="image/png" sizes="96x96" href="Content/Images/favicon.ico">
</head>
<body>
    <!-- WRAPPER -->
    <div id="wrapper">
        <!-- SIDEBAR -->
        <div class="sidebar">
            <div class="brand">
                <center>
                    <a href="@Url.Content("~/Home")"><img src="../../Content/Images/logo.png" alt="Broadvine Logo" class="img-responsive logo"></a>
                </center>
            </div>
            <div class="sidebar-scroll">
                <nav>
                    <ul class="nav">
                        <li><a id="menu-home" href="/Home" class="menu-item"><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
                        <li><a id="menu-invoice-pending" href="/Invoices?status=0" class="menu-item"><i class="lnr lnr-file-empty"></i> <span>Pending Invoices</span></a></li>
                        <li><a id="menu-invoice-post" href="/Invoices?status=2" class="menu-item"><i class="lnr lnr-phone-handset"></i> <span>Pending Answerback</span></a></li>
                        <li><a id="menu-invoice-posted" href="/Invoices?status=3" class="menu-item"><i class="fa fa-money"></i> <span>Pending Payment</span></a></li>
                        <li><a id="menu-invoice-paid" href="/Invoices?status=4" class="menu-item"><i class="fa fa-check"></i> <span>Paid Invoices</span></a></li>
                        <li><a id="menu-invoice-void" href="/Invoices?status=9" class="menu-item"><i class="fa fa-xing"></i> <span>Void Invoices</span></a></li>
                        <li><a id="menu-invoice-reject" href="/Invoices?status=-1" class="menu-item"><i class="lnr lnr-exit"></i> <span>Rejected Invoices</span></a></li>
                        <li><a id="menu-invoice-failed" href="/Invoices?status=99" class="menu-item"><i class="lnr lnr-alarm"></i> <span>Failed Invoices</span></a></li>

                        @if (this.User.Identity.IsAuthenticated)
                        {
                            if (this.User.IsInRole("Sysop"))
                            {
                                <li><a id="menu-customer" href="@Url.Content("~/Customers")" class="menu-item"><i class="lnr lnr-home"></i> <span>Customers</span></a></li>
                                <li><a id="menu-user" href="/Users" class="menu-item"><i class="lnr lnr-users"></i> <span>User Accounts</span></a></li>
                                @*<li><a id="menu-role" href="/Roles" class="menu-item"><i class="lnr lnr-users"></i> <span>User Roles</span></a></li>*@
                                <li><a id="menu-property" href="@Url.Content("~/Properties/Index")" class="menu-item"><i class="lnr lnr-home"></i> <span>Properties</span></a></li>
                            }
                        }
                        
                    </ul>
                </nav>
            </div>
            
        </div>
        <!-- END SIDEBAR -->
        <!-- MAIN -->
        <div class="main">
            <!-- NAVBAR -->
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-btn">
                        <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
                    </div>
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-menu">
                            <span class="sr-only">Toggle Navigation</span>
                            <i class="fa fa-bars icon-nav"></i>
                        </button>
                    </div>
                    <div id="navbar-menu" class="navbar-collapse collapse">
                        @using (Html.BeginForm("Search", "Invoices", FormMethod.Get, new { @class = "navbar-form navbar-left hidden-xs" }))
                        {
                            <div class="input-group">
                                @Html.TextBox("searchterm","", new { @class="form-control", @placeholder = "Invoice #..."})
                                <span class="input-group-btn">
                                    <input type="submit" value="Go" class="btn btn-primary" />
                                </span>
                            </div>
                        }

                        <ul class="nav navbar-nav navbar-right">
                            @*<li class="dropdown">
                                <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                                    <i class="lnr lnr-alarm"></i>
                                    <span class="badge bg-danger">5</span>
                                </a>
                                <ul class="dropdown-menu notifications">
                                    <li><a href="#" class="notification-item"><span class="dot bg-warning"></span>System space is almost full</a></li>
                                    <li><a href="#" class="notification-item"><span class="dot bg-danger"></span>You have 9 unfinished tasks</a></li>
                                    <li><a href="#" class="notification-item"><span class="dot bg-success"></span>Monthly report is available</a></li>
                                    <li><a href="#" class="notification-item"><span class="dot bg-warning"></span>Weekly meeting in 1 hour</a></li>
                                    <li><a href="#" class="notification-item"><span class="dot bg-success"></span>Your request has been approved</a></li>
                                    <li><a href="#" class="more">See all notifications</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="lnr lnr-question-circle"></i> <span>Help</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Basic Use</a></li>
                                    <li><a href="#">Working With Data</a></li>
                                    <li><a href="#">Security</a></li>
                                    <li><a href="#">Troubleshooting</a></li>
                                </ul>
                            </li>*@
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">@*<img src="Content/Images/user.png" class="img-circle" alt="Avatar">*@ <span>@(this.User.Identity.Name)</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Content("~/Users/Details/")"><i class="lnr lnr-user"></i> <span>My Account</span></a></li>
                                    <li><a href="@Url.Content("~/Account/LogOff/")"><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- END NAVBAR -->
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
            <!-- END MAIN CONTENT -->
            @*<footer>
                <div class="container-fluid">
                </div>
            </footer>*@
        </div>
        <!-- END MAIN -->
    </div>
    <!-- END WRAPPER -->
    <!-- Javascript -->

    @Scripts.Render("~/bundles/jquery", "~/bundles/jqueryui", "~/bundles/bootstrap", "~/bundles/misc", "~/bundles/kendo")
    @RenderSection("scripts", required: false)
</body>
</html>